const express = require("express");
const mongoose = require("mongoose");
const multer = require("multer");

const Story = require("../models/Story");
const StorySetting = require("../models/StorySetting");
const Conversation = require("../models/Conversation");
const Message = require("../models/Message");
const Notification = require("../models/Notification");
const auth = require("../middleware/auth");
const cloudinary = require("../config/cloudinary");
const { enforceContactSafety, hasMessagingRestriction } = require("../utils/contactSafety");

const router = express.Router();
const upload = multer({storage:multer.memoryStorage(),limits:{fileSize:30*1024*1024,files:2},fileFilter(req,file,callback){const mime=String(file?.mimetype||"").toLowerCase();if(mime.startsWith("image/")||mime.startsWith("video/")||mime.startsWith("audio/"))return callback(null,true);callback(new Error("Stories support image, video, and audio uploads only"));}});
const storyUpload=upload.fields([{name:"file",maxCount:1},{name:"musicFile",maxCount:1}]);
function validId(value){return mongoose.Types.ObjectId.isValid(value);}function storyAuthorFields(){return "name companyName schoolName role profileImage logo avatar headline profession course";}function clampNumber(value,min,max,fallback){const number=Number(value);if(!Number.isFinite(number))return fallback;return Math.max(min,Math.min(max,number));}function parseJSON(value,fallback){if(value===undefined||value===null||value==="")return fallback;if(typeof value!=="string")return value;try{return JSON.parse(value);}catch{return fallback;}}
function normalizeStoryElements(raw){const source=Array.isArray(raw)?raw.slice(0,40):[];return source.map(item=>{const kind=["text","caption","mention"].includes(item?.kind)?item.kind:"text",user=validId(item?.user)?item.user:null;return{kind,text:String(item?.text||"").trim().slice(0,500),user,x:clampNumber(item?.x,0,100,50),y:clampNumber(item?.y,0,100,50),scale:clampNumber(item?.scale,.4,4,1),rotation:clampNumber(item?.rotation,-360,360,0),font:String(item?.font||"Inter").trim().slice(0,80),fontSize:clampNumber(item?.fontSize,12,120,34),color:String(item?.color||"#ffffff").trim().slice(0,32),align:["left","center","right"].includes(item?.align)?item.align:"center",style:["clean","strong","typewriter","neon","classic"].includes(item?.style)?item.style:"clean"};}).filter(item=>item.text||item.user);}
function normalizeTaggedUsers(raw,elements){const values=Array.isArray(raw)?raw:[],ids=new Set(values.filter(validId).map(String));elements.forEach(item=>{if(item.kind==="mention"&&validId(item.user))ids.add(String(item.user));});return[...ids].slice(0,30);}
function storyPayload(story,viewerId){const value=story.toObject?story.toObject({virtuals:true}):{...story},viewers=Array.isArray(value.viewers)?value.viewers:[],likes=Array.isArray(value.likes)?value.likes:[],owner=String(value.author?._id||value.author)===String(viewerId);value.seen=viewers.some(item=>String(item?.user?._id||item?.user||"")===String(viewerId));value.viewerCount=viewers.length;value.likedByMe=likes.some(user=>String(user?._id||user||"")===String(viewerId));if(owner)value.privateLikeCount=likes.length;delete value.likeCount;if(!owner){delete value.viewers;delete value.likes;delete value.privateLikeCount;}return value;}
async function uploadStoryAsset(file,folder){if(!file)return null;const mime=String(file.mimetype||"").toLowerCase(),isVideo=mime.startsWith("video/"),isAudio=mime.startsWith("audio/"),resourceType=isVideo||isAudio?"video":"image";return new Promise((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder,resource_type:resourceType},(error,result)=>{if(error)return reject(error);resolve({url:result.secure_url,publicId:result.public_id,mimeType:file.mimetype,type:isVideo?"video":isAudio?"audio":"image"});});stream.end(file.buffer);});}
async function directContactIds(userId){const normalized=String(userId),conversations=await Conversation.find({type:"direct",participantIds:userId}).select("participants").lean(),ids=new Set([normalized]);conversations.forEach(conversation=>{const participants=Array.isArray(conversation.participants)?conversation.participants:[],self=participants.find(participant=>String(participant?.user||"")===normalized);if(!self||self.isActive===false||self.blocked===true)return;participants.forEach(participant=>{const id=String(participant?.user||"");if(id&&id!==normalized&&participant.isActive!==false&&participant.blocked!==true)ids.add(id);});});return[...ids].filter(validId).map(id=>new mongoose.Types.ObjectId(id));}
async function mutedStoryAuthorIds(userId){const settings=await StorySetting.find({user:userId,muted:true}).select("author").lean();return settings.map(item=>item.author).filter(Boolean);}
async function findOrCreateDirectConversation(userA,userB,createdBy){let conversation=await Conversation.findOne({type:"direct",participantIds:{$all:[userA,userB]}});if(conversation)return conversation;return Conversation.create({type:"direct",createdBy,participants:[{user:userA,role:"member"},{user:userB,role:"member"}],participantIds:[userA,userB],metadata:{source:"story_reply"}});}
async function canViewStory(story,userId){if(String(story.author)===String(userId)||story.audience==="everyone")return true;const contacts=await directContactIds(userId);return contacts.some(id=>String(id)===String(story.author));}
async function emitStoryEvent(req,story,eventName,extra={}){const io=req.app.get("io")||req.io;if(!io||!story)return;const authorId=String(story.author?._id||story.author||req.user._id),payload={storyId:String(story._id),authorId,event:eventName,...extra};if(story.audience==="everyone"){io.emit(eventName,payload);return;}const contacts=await directContactIds(authorId),recipients=new Set([authorId,...contacts.map(String)]);recipients.forEach(userId=>io.to(userId).emit(eventName,payload));}
async function upsertStoryNotification({user,type,sender,storyId,text}){if(!validId(user)||!validId(sender)||!validId(storyId)||String(user)===String(sender))return null;return Notification.findOneAndUpdate({user,type,sender,"metadata.storyId":String(storyId)},{$set:{text,link:"messages.html",read:false,metadata:{storyId:String(storyId),source:"story"}}},{upsert:true,new:true,setDefaultsOnInsert:true});}
async function notifyStoryMentions(story,authorId){const ids=[...new Set((story.taggedUsers||[]).map(item=>String(item?._id||item)).filter(validId))];await Promise.all(ids.filter(id=>id!==String(authorId)).map(user=>upsertStoryNotification({user,type:"story_mention",sender:authorId,storyId:story._id,text:"mentioned you in a story"}).catch(()=>null)));}

router.get("/",auth,async(req,res)=>{try{const now=new Date(),[contactIds,mutedAuthorIds]=await Promise.all([directContactIds(req.user._id),mutedStoryAuthorIds(req.user._id)]),mutedSet=new Set(mutedAuthorIds.map(String));const stories=await Story.find({deletedAt:null,expiresAt:{$gt:now},$or:[{author:req.user._id},{audience:"everyone"},{audience:"connections",author:{$in:contactIds}}]}).populate("author",storyAuthorFields()).populate("elements.user",storyAuthorFields()).populate("taggedUsers",storyAuthorFields()).sort({createdAt:1}),grouped=new Map();stories.forEach(story=>{const authorId=String(story.author?._id||story.author),isOwner=authorId===String(req.user._id);if(!isOwner&&mutedSet.has(authorId))return;if(!grouped.has(authorId))grouped.set(authorId,{author:story.author,stories:[],hasUnseen:false,latestAt:story.createdAt});const group=grouped.get(authorId),payload=storyPayload(story,req.user._id);group.stories.push(payload);group.hasUnseen=group.hasUnseen||!payload.seen;group.latestAt=story.createdAt;});const groups=[...grouped.values()].sort((a,b)=>a.hasUnseen!==b.hasUnseen?(a.hasUnseen?-1:1):new Date(b.latestAt)-new Date(a.latestAt));res.json({groups});}catch(error){console.error("GET STORIES ERROR:",error);res.status(500).json({message:"Unable to load stories"});}});
router.get("/settings/muted",auth,async(req,res)=>{try{const settings=await StorySetting.find({user:req.user._id,muted:true}).populate("author",storyAuthorFields()).sort({mutedAt:-1}).lean();res.json({mutedAuthors:settings.map(item=>({author:item.author,muted:true,mutedAt:item.mutedAt||item.updatedAt}))});}catch(error){console.error("GET MUTED STORIES ERROR:",error);res.status(500).json({message:"Unable to load muted stories"});}});
router.post("/",auth,storyUpload,async(req,res)=>{try{const text=String(req.body?.text||"").trim(),audience=req.body?.audience==="everyone"?"everyone":"connections",mediaFile=req.files?.file?.[0]||null,musicFile=req.files?.musicFile?.[0]||null;if(mediaFile&&String(mediaFile.mimetype||"").startsWith("audio/"))return res.status(400).json({message:"Use the music control for audio. Story media must be a photo or video."});const elements=normalizeStoryElements(parseJSON(req.body?.elements,[])),taggedUsers=normalizeTaggedUsers(parseJSON(req.body?.taggedUsers,[]),elements);if(!text&&!mediaFile&&!elements.length)return res.status(400).json({message:"Add text, a photo, or a video to your story"});const[media,uploadedMusic]=await Promise.all([uploadStoryAsset(mediaFile,"aift/stories"),uploadStoryAsset(musicFile,"aift/stories/music")]),musicMeta=parseJSON(req.body?.music,{})||{},music=uploadedMusic||musicMeta?.url?{url:uploadedMusic?.url||String(musicMeta.url||"").trim(),publicId:uploadedMusic?.publicId||"",mimeType:uploadedMusic?.mimeType||String(musicMeta.mimeType||"").trim(),title:String(musicMeta.title||musicFile?.originalname||"Music").trim().slice(0,180),artist:String(musicMeta.artist||"").trim().slice(0,180),coverUrl:String(musicMeta.coverUrl||"").trim().slice(0,1000),startAt:clampNumber(musicMeta.startAt,0,36000,0),duration:clampNumber(musicMeta.duration,0,120,15),volume:clampNumber(musicMeta.volume,0,1,1),muted:musicMeta.muted===true,source:uploadedMusic?"upload":["aift_catalog","external"].includes(musicMeta.source)?musicMeta.source:"external"}:undefined;const story=await Story.create({author:req.user._id,type:media?.type||"text",text,mediaUrl:media?.url||"",mediaPublicId:media?.publicId||"",mediaMimeType:media?.mimeType||"",background:"",elements,taggedUsers,music,audience,expiresAt:new Date(Date.now()+24*60*60*1000)});await story.populate("author",storyAuthorFields());await story.populate("elements.user",storyAuthorFields());await story.populate("taggedUsers",storyAuthorFields());await Promise.all([emitStoryEvent(req,story,"storyCreated"),notifyStoryMentions(story,req.user._id)]);res.status(201).json({story:storyPayload(story,req.user._id)});}catch(error){console.error("CREATE STORY ERROR:",error);res.status(500).json({message:error.message||"Unable to create story"});}});
router.patch("/authors/:authorId/mute",auth,async(req,res)=>{try{const authorId=String(req.params.authorId||"");if(!validId(authorId))return res.status(400).json({message:"Invalid story author ID"});if(authorId===String(req.user._id))return res.status(400).json({message:"You cannot mute your own stories"});const muted=req.body?.muted!==false,setting=await StorySetting.findOneAndUpdate({user:req.user._id,author:authorId},{$set:{muted,mutedAt:muted?new Date():null},$setOnInsert:{user:req.user._id,author:authorId}},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({authorId,muted:!!setting.muted,mutedAt:setting.mutedAt||null});}catch(error){console.error("MUTE STORY AUTHOR ERROR:",error);res.status(500).json({message:"Unable to update story preference"});}});
router.patch("/:id/view",auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({message:"Invalid story ID"});const story=await Story.findOne({_id:req.params.id,deletedAt:null,expiresAt:{$gt:new Date()}});if(!story)return res.status(404).json({message:"Story not found"});if(!(await canViewStory(story,req.user._id)))return res.status(403).json({message:"You cannot view this story"});const isOwner=String(story.author)===String(req.user._id),alreadyViewed=story.viewers.some(item=>String(item.user)===String(req.user._id));if(!alreadyViewed&&!isOwner){story.viewers.push({user:req.user._id,viewedAt:new Date()});await story.save();const io=req.app.get("io")||req.io;io?.to?.(String(story.author)).emit("storyViewed",{storyId:String(story._id),viewerCount:story.viewers.length});}res.json({seen:true,viewerCount:story.viewers.length});}catch(error){console.error("VIEW STORY ERROR:",error);res.status(500).json({message:"Unable to mark story as viewed"});}});
router.patch("/:id/like",auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({message:"Invalid story ID"});const story=await Story.findOne({_id:req.params.id,deletedAt:null,expiresAt:{$gt:new Date()}});if(!story)return res.status(404).json({message:"Story not found or has expired"});if(!(await canViewStory(story,req.user._id)))return res.status(403).json({message:"You cannot like this story"});if(String(story.author)===String(req.user._id))return res.status(400).json({message:"You cannot like your own story"});const userId=String(req.user._id),index=story.likes.findIndex(id=>String(id)===userId),liked=index<0;if(liked)story.likes.push(req.user._id);else story.likes.splice(index,1);await story.save();if(liked)await upsertStoryNotification({user:story.author,type:"story_like",sender:req.user._id,storyId:story._id,text:"liked your story"}).catch(()=>null);else await Notification.deleteMany({user:story.author,type:"story_like",sender:req.user._id,"metadata.storyId":String(story._id)}).catch(()=>null);const io=req.app.get("io")||req.io;io?.to?.(String(story.author)).emit("storyLiked",{storyId:String(story._id),userId,liked,likeCount:story.likes.length});res.json({storyId:String(story._id),liked});}catch(error){console.error("LIKE STORY ERROR:",error);res.status(500).json({message:"Unable to update story like"});}});
router.get("/:id/likes",auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({message:"Invalid story ID"});const story=await Story.findById(req.params.id).populate("likes",storyAuthorFields());if(!story)return res.status(404).json({message:"Story not found"});if(String(story.author)!==String(req.user._id))return res.status(403).json({message:"Only the story owner can view likes"});res.json({likes:story.likes||[]});}catch(error){console.error("STORY LIKES ERROR:",error);res.status(500).json({message:"Unable to load story likes"});}});
router.post("/:id/reply",auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({message:"Invalid story ID"});const text=String(req.body?.text||"").trim();if(!text)return res.status(400).json({message:"Reply text is required"});if(text.length>4000)return res.status(400).json({message:"Story reply is too long"});const story=await Story.findOne({_id:req.params.id,deletedAt:null,expiresAt:{$gt:new Date()}});if(!story)return res.status(404).json({message:"Story not found or has expired"});const authorId=String(story.author),senderId=String(req.user._id);if(authorId===senderId)return res.status(400).json({message:"You cannot reply to your own story"});if(!(await canViewStory(story,req.user._id)))return res.status(403).json({message:"You cannot reply to this story"});if(await hasMessagingRestriction(senderId))return res.status(403).json({code:"AIFT_MESSAGING_RESTRICTED",message:"Messaging is restricted pending AIFT review."});const safety=await enforceContactSafety({user:req.user,text,receiverId:authorId});if(!safety.allowed)return res.status(safety.statusCode).json({code:"AIFT_CONTACT_SHARING_BLOCKED",message:safety.message,warningNumber:safety.warningNumber,action:safety.action});const conversation=await findOrCreateDirectConversation(senderId,authorId,senderId),storyPreview=story.text?story.text.slice(0,180):story.type==="video"?"Video story":story.type==="image"?"Photo story":"Story",message=await Message.create({conversationId:conversation._id,sender:senderId,receiver:authorId,participants:[senderId,authorId],text,messageType:"text",metadata:{source:"story_reply",storyId:String(story._id),storyAuthorId:authorId,storyType:story.type,storyPreview,storyMediaUrl:story.mediaUrl||""}});conversation.setLastMessage(message);conversation.incrementUnreadForOthers(senderId);await conversation.save();const populated=await Message.findById(message._id).populate("sender","name companyName schoolName role profileImage logo").populate("receiver","name companyName schoolName role profileImage logo");await upsertStoryNotification({user:authorId,type:"story_reply",sender:senderId,storyId:story._id,text:"replied to your story"}).catch(()=>null);const io=req.app.get("io")||req.io;io?.to(String(authorId)).emit("newMessage",populated);io?.to(String(senderId)).emit("newMessage",populated);res.status(201).json({success:true,conversationId:conversation._id,message:populated});}catch(error){console.error("STORY REPLY ERROR:",error);res.status(500).json({message:"Unable to send story reply"});}});
router.get("/:id/viewers",auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({message:"Invalid story ID"});const story=await Story.findById(req.params.id).populate("viewers.user",storyAuthorFields()).populate("likes",storyAuthorFields());if(!story)return res.status(404).json({message:"Story not found"});if(String(story.author)!==String(req.user._id))return res.status(403).json({message:"Only the story owner can view viewers"});const ownerId=String(req.user._id),likedIds=new Set((story.likes||[]).map(user=>String(user?._id||user))),directConversations=await Conversation.find({type:"direct",participantIds:req.user._id}).select("_id participants participantIds").lean(),conversationByViewer=new Map();directConversations.forEach(conversation=>{const ids=Array.isArray(conversation.participantIds)?conversation.participantIds.map(String):(conversation.participants||[]).map(participant=>String(participant?.user||"")).filter(Boolean),otherId=ids.find(id=>id&&id!==ownerId);if(otherId&&!conversationByViewer.has(otherId))conversationByViewer.set(otherId,String(conversation._id));});const viewers=(story.viewers||[]).map(item=>{const value=item.toObject?item.toObject():{...item},viewerId=String(value.user?._id||value.user||"");return{...value,liked:likedIds.has(viewerId),conversationId:conversationByViewer.get(viewerId)||null};});res.json({viewers,viewerCount:viewers.length});}catch(error){console.error("STORY VIEWERS ERROR:",error);res.status(500).json({message:"Unable to load story viewers"});}});
router.delete("/:id",auth,async(req,res)=>{try{if(!validId(req.params.id))return res.status(400).json({message:"Invalid story ID"});const story=await Story.findOne({_id:req.params.id,author:req.user._id});if(!story)return res.status(404).json({message:"Story not found"});story.deletedAt=new Date();await story.save();await Notification.deleteMany({"metadata.storyId":String(story._id)}).catch(()=>null);if(story.mediaPublicId){const resourceType=story.type==="video"?"video":"image";cloudinary.uploader.destroy(story.mediaPublicId,{resource_type:resourceType}).catch(()=>{});}if(story.music?.publicId)cloudinary.uploader.destroy(story.music.publicId,{resource_type:"video"}).catch(()=>{});await emitStoryEvent(req,story,"storyDeleted");res.json({success:true});}catch(error){console.error("DELETE STORY ERROR:",error);res.status(500).json({message:"Unable to delete story"});}});
router.use((error,req,res,next)=>{if(error instanceof multer.MulterError)return res.status(400).json({message:error.code==="LIMIT_FILE_SIZE"?"Story media must be 30MB or smaller":error.message});if(error)return res.status(400).json({message:error.message||"Invalid story upload"});next();});
module.exports=router;
