"use strict";

const rateLimit = require("express-rate-limit");

const analyticsRateLimit = rateLimit({
  windowMs: 60 * 1000,
  limit: 120,

  standardHeaders: "draft-7",
  legacyHeaders: false,

  /*
    Use the anonymized IP-derived key generated by
    analyticsContext when available.
  */
  keyGenerator(req) {
    return (
      req.analyticsContext?.actorId?.toString() ||
      req.analyticsContext?.sessionId ||
      req.analyticsContext?.ipHash ||
      req.ip
    );
  },

  handler(req, res) {
    return res.status(429).json({
      success: false,
      message:
        "Too many analytics events. Please try again shortly."
    });
  },

  skip(req) {
    return req.method === "OPTIONS";
  }
});

module.exports = analyticsRateLimit;
